<?php

namespace ContainerItYsVGi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TJcaXyrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tJcaXyr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tJcaXyr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gamesEvents' => ['privates', '.errored..service_locator.tJcaXyr.App\\Entity\\GamesEvents', NULL, 'Cannot autowire service ".service_locator.tJcaXyr": it needs an instance of "App\\Entity\\GamesEvents" but this type has been excluded in "config/services.yaml".'],
            'gamesEventsRepository' => ['privates', 'App\\Repository\\GamesEventsRepository', 'getGamesEventsRepositoryService', true],
        ], [
            'gamesEvents' => 'App\\Entity\\GamesEvents',
            'gamesEventsRepository' => 'App\\Repository\\GamesEventsRepository',
        ]);
    }
}
