<?php

namespace ContainerItYsVGi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiInvitacionUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\ApiInvitacionUser' shared autowired service.
     *
     * @return \App\Controller\Api\ApiInvitacionUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'ApiInvitacionUser.php';

        $container->services['App\\Controller\\Api\\ApiInvitacionUser'] = $instance = new \App\Controller\Api\ApiInvitacionUser(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['App\\Service\\Correo'] ?? $container->load('getCorreoService')));

        $instance->setContainer(($container->privates['.service_locator.LFpjZXt'] ?? $container->load('get_ServiceLocator_LFpjZXtService'))->withContext('App\\Controller\\Api\\ApiInvitacionUser', $container));

        return $instance;
    }
}
