<?php

namespace ContainerItYsVGi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGamesEventsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tJcaXyr.App\Entity\GamesEvents' shared service.
     *
     * @return \App\Entity\GamesEvents
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tJcaXyr": it needs an instance of "App\\Entity\\GamesEvents" but this type has been excluded in "config/services.yaml".');
    }
}
