<?php

namespace ContainerItYsVGi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJuego2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c7W55EL.App\Entity\Juego' shared service.
     *
     * @return \App\Entity\Juego
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.c7W55EL": it needs an instance of "App\\Entity\\Juego" but this type has been excluded in "config/services.yaml".');
    }
}
