vich_uploader:
    db_driver: orm

    mappings:
       juego:
            uri_prefix: /images/juegos
            upload_destination: '%kernel.project_dir%/public/images/juegos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # uri_prefix:         '%app.path.juego_images%'
        #   upload_destination: '%kernel.project_dir%/public%app.path.juego_images%'
        #    namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
