<?php

namespace ContainerCEVyUMV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C7W55ELService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c7W55EL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c7W55EL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'juego' => ['privates', '.errored..service_locator.c7W55EL.App\\Entity\\Juego', NULL, 'Cannot autowire service ".service_locator.c7W55EL": it needs an instance of "App\\Entity\\Juego" but this type has been excluded in "config/services.yaml".'],
            'juegoRepository' => ['privates', 'App\\Repository\\JuegoRepository', 'getJuegoRepositoryService', true],
        ], [
            'juego' => 'App\\Entity\\Juego',
            'juegoRepository' => 'App\\Repository\\JuegoRepository',
        ]);
    }
}
