<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCEVyUMV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCEVyUMV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCEVyUMV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCEVyUMV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCEVyUMV\App_KernelDevDebugContainer([
    'container.build_hash' => 'CEVyUMV',
    'container.build_id' => 'b4fa81b7',
    'container.build_time' => 1678180651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCEVyUMV');
